### ISSUE TITLE
[Feature] Installer should offer to place a shortcut on the desktop

### ISSUE THREAD

**Issue by SchaffRita** [Ayagikei/LifeUp-Desktop#13]
During the LifeUp Desktop installation, the path to where the software is installed is asked but not if a shortcut should be placed on the desktop.
After the installation, if a user tries to open the application, they won't be able to find the shortcut on the desktop or in the Windows Start menu.

Please include the option to set shortcuts at the following places:
- Start Menu
- Desktop

**Comment by Ayagikei** [comment]
Thanks for the issue!

We will add the `shortcut` package param in the next release(v1.1.0).
