### ISSUE TITLE
Failed to Launch JVM

### ISSUE THREAD

**Issue by MarioZZJ** [Ayagikei/LifeUp-Desktop#2]
* 系统：Windows 11 Pro 22H2

安装到文件夹后点击打开LifeUp Desktop.exe弹窗如下

<img width="312" alt="image" src="https://user-images.githubusercontent.com/52254876/218505350-20fe364a-55b3-4eed-bbb7-d78e5820d668.png">

**Comment by MarioZZJ** [comment]
我是在 release 下载的 msi 安装包，文档里面链接的 dfyun 超级慢……

**Comment by Ayagikei** [comment]
> 我是在 release 下载的 msi 安装包，文档里面链接的 dfyun 超级慢……

为了节省成本，那个 CDN 确实比较慢。

这个问题我稍后排查下（不确定正式包是否会输出完整的错误日志，如果有的话可以提供一下）。

**Comment by MarioZZJ** [comment]
没有输出日志。但是我在另外一台java17的win10上可以启动，要是能输出日志排查下就好了

发自我的小米
在 AyagiKei ***@***.***>，2023年2月14日 19:05写道：

我是在 release 下载的 msi 安装包，文档里面链接的 dfyun 超级慢……

为了节省成本，那个 CDN 确实比较慢。

这个问题我稍后排查下（不确定正式包是否会输出完整的错误日志，如果有的话可以提供一下）。

**Comment by Ayagikei** [comment]
> 没有输出日志。但是我在另外一台java17的win10上可以启动，要是能输出日志排查下就好了 发自我的小米 在 AyagiKei ***@***.***>，2023年2月14日 19:05写道： 我是在 release 下载的 msi 安装包，文档里面链接的 dfyun 超级慢…… 为了节省成本，那个 CDN 确实比较慢。 这个问题我稍后排查下（不确定正式包是否会输出完整的错误日志，如果有的话可以提供一下）。 — Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAyagikei%2FLifeUp-Desktop%2Fissues%2F2%23issuecomment-1429538779&data=05%7C01%7C%7Cd3e23e6d333a466e6aa708db0e7b58ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638119695152818600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lnhQ%2BHVSApUojptJuPVZm3GlDwSdUN7%2FVDP%2FJCdZiqw%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMOVRHCBVFNU5YZWFD6I7D3WXNRGTANCNFSM6AAAAAAU2N3H34&data=05%7C01%7C%7Cd3e23e6d333a466e6aa708db0e7b58ff%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638119695152818600%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dWNEjN05qsrQndnAFCptsczXZC6g%2FhZY8vkZ8q%2F8NyQ%3D&reserved=0>. You are receiving this because you authored the thread.Message ID: ***@***.***>

嗯，我们稍后试试加一下崩溃日志输出。

我这边也是 Win 11 Pro 22H2，但运行正常。我这边先排查是不是发布配置的问题。

**Comment by Ayagikei** [comment]
久等，方便的话可以尝试一下 1.0.2 版本：
[https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2](https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2)

加上了错误堆栈弹窗，以及打包时的配置有些调整。

**Comment by MarioZZJ** [comment]
> 久等，方便的话可以尝试一下 1.0.2 版本： https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2
> 
> 加上了错误堆栈弹窗，以及打包时的配置有些调整。

感谢！但是不知道为什么好像还是这个弹窗……难道是程序之外的问题

**Comment by MarioZZJ** [comment]
![image](https://user-images.githubusercontent.com/52254876/219992325-23230ef1-c196-40ec-87c7-b4e5b135adb2.png)
![image](https://user-images.githubusercontent.com/52254876/219992353-c120b9b0-23f7-4651-8c33-14c2bb24986b.png)

**Comment by Ayagikei** [comment]
> > 久等，方便的话可以尝试一下 1.0.2 版本： https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2
> > 加上了错误堆栈弹窗，以及打包时的配置有些调整。
> 
> 感谢！但是不知道为什么好像还是这个弹窗……难道是程序之外的问题

触及到知识盲区了，好像没跑到我们的异常处理逻辑里。😥

理论上产物应该内置了 JRE，也有可能是什么兼容性问题。

要排查的话，可能需要你那边安装一下 IntelliJ IDEA 实际跑一下项目试试。

**Comment by MarioZZJ** [comment]
> > > 久等，方便的话可以尝试一下 1.0.2 版本： https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2
> > > 加上了错误堆栈弹窗，以及打包时的配置有些调整。
> > 
> > 
> > 感谢！但是不知道为什么好像还是这个弹窗……难道是程序之外的问题
> 
> 触及到知识盲区了，好像没跑到我们的异常处理逻辑里。😥
> 
> 理论上产物应该内置了 JRE，也有可能是什么兼容性问题。
> 
> 要排查的话，可能需要你那边安装一下 IntelliJ IDEA 实际跑一下项目试试。

在 IDEA 里面 Gradle `run` 了，能打开界面且可以正常使用，感觉软件做的不错。

但是不知道为什么 `packageMsi` 出来自己打包的 msi 安装后还是这个情况……有什么方法可以看这个日志排查问题吗

**Comment by Ayagikei** [comment]
> > > > 久等，方便的话可以尝试一下 1.0.2 版本： https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2
> > > > 加上了错误堆栈弹窗，以及打包时的配置有些调整。
> > > 
> > > 
> > > 感谢！但是不知道为什么好像还是这个弹窗……难道是程序之外的问题
> > 
> > 
> > 触及到知识盲区了，好像没跑到我们的异常处理逻辑里。😥
> > 理论上产物应该内置了 JRE，也有可能是什么兼容性问题。
> > 要排查的话，可能需要你那边安装一下 IntelliJ IDEA 实际跑一下项目试试。
> 
> 在 IDEA 里面 Gradle `run` 了，能打开界面且可以正常使用，感觉软件做的不错。
> 
> 但是不知道为什么 `packageMsi` 出来自己打包的 msi 安装后还是这个情况……有什么方法可以看这个日志排查问题吗

可以试试跑一下`runDistributable`/`runReleaseDistributable` 看看有没有问题。
或者查看 `packageMsi` 安装后的路径，崩溃后看看会不会崩溃日志文件（之前在调试期间好像出现过，不过崩溃时机有点不一样）。

我这边也不太了解 compose desktop 产物崩溃的日志查看方式，根据 https://github.com/JetBrains/compose-jb/issues/187 的说法，可能可以试试用命令行启动应用。

**Comment by MarioZZJ** [comment]
> > > > > 久等，方便的话可以尝试一下 1.0.2 版本： https://github.com/Ayagikei/LifeUp-Desktop/releases/tag/1.0.2
> > > > > 加上了错误堆栈弹窗，以及打包时的配置有些调整。
> > > > 
> > > > 
> > > > 感谢！但是不知道为什么好像还是这个弹窗……难道是程序之外的问题
> > > 
> > > 
> > > 触及到知识盲区了，好像没跑到我们的异常处理逻辑里。😥
> > > 理论上产物应该内置了 JRE，也有可能是什么兼容性问题。
> > > 要排查的话，可能需要你那边安装一下 IntelliJ IDEA 实际跑一下项目试试。
> > 
> > 
> > 在 IDEA 里面 Gradle `run` 了，能打开界面且可以正常使用，感觉软件做的不错。
> > 但是不知道为什么 `packageMsi` 出来自己打包的 msi 安装后还是这个情况……有什么方法可以看这个日志排查问题吗
> 
> 可以试试跑一下`runDistributable`/`runReleaseDistributable` 看看有没有问题。 或者查看 `packageMsi` 安装后的路径，崩溃后看看会不会崩溃日志文件（之前在调试期间好像出现过，不过崩溃时机有点不一样）。
> 
> 我这边也不太了解 compose desktop 产物崩溃的日志查看方式，根据 [JetBrains/compose-jb#187](https://github.com/JetBrains/compose-jb/issues/187) 的说法，可能可以试试用命令行启动应用。

感谢，`runDistributable` 后调试好了。报错内容是：

```
Assistive Technology not found: com.sun.java.accessibility.AccessBridge
```

参考网上的做法是将 `~/.accessibility.properties` 文件的以下两行注册即可：

```
# assistive_technologies=com.sun.java.accessibility.AccessBridge
# screen_magnifier_present=true
```

修改后，程序可以正常运行。

**Comment by Ayagikei** [comment]
> Assistive Technology not found: com.sun.java.accessibility.AccessBridge

感谢提供信息！
